services:
  - type: web
    name: pdf-extractor-api
    runtime: docker
    plan: free
    dockerfilePath: ./Dockerfile
    envVars:
      - key: SUPABASE_URL
        sync: false
      - key: SUPABASE_SECRET_KEY
        sync: false
      - key: SUPABASE_KEY
        sync: false
      - key: SUPABASE_JWT_SIGNING_KEY
        sync: false
      - key: GOOGLE_API_KEY
        sync: false
      - key: OLLAMA_HOST
        sync: false
      - key: LLM_PROVIDER
        value: gemini
      - key: FRONTEND_URL
        sync: false
      - key: PORT
        value: "8000"
